title: "Victor Nwoke"
email: "yourname@email.com"
description: "Registered Retirement Brokerage Rep | Forex Trader | Crypto Enthusiast | Entrepreneur"
baseurl: ""
url: "https://kunlesanni.com"
linkedin_username: victornwoke

theme: jekyll-theme-minimal
